### ISSUE TITLE
Setting Controlling OwnerRef on resource likely not in our namespace

### ISSUE THREAD

**Issue by djzager** [open-cluster-management/multicluster-inventory#30]
https://github.com/open-cluster-management/multicluster-inventory/blob/master/pkg/controller/baremetalasset/baremetalasset_controller.go#L437-L446

We either need to make the BareMetalAsset a non-namespaced resource (put it at the cluster scope) or come up with another mechanism for getting events on SyncSets related to our BareMetalAsset.

**Comment by mhrivnak** [comment]
Good catch. We got feedback that keeping BMAs namespaced is valuable. I agree with that and think we should keep it as such.

We should probably do this:
* stop putting an owner ref on SyncSets. As-is, they are subject to getting garbage-collected unexpectedly; yikes!
* put a finalizer on the SyncSets plus some reference to the BareMetalAsset. I wonder if anyone's ever encoded a resource reference directly into the finalizer. For example it could be `<name>.<namespace>.baremetalasset.midas.io` or something like that. If that's a bad idea for some reason, then perhaps just an annotation.
* use a mapping handler to enqueue the corresponding BMA for reconciliation when a SyncSet has an event.

Thoughts on that?

**Comment by sacharya** [comment]
> use a mapping handler to enqueue the corresponding BMA for reconciliation when a SyncSet has an event.

We already do something similar for ClusterDeployment events. We could do the same for SyncSets.

**Comment by djzager** [comment]
> * put a finalizer on the SyncSets plus some reference to the BareMetalAsset. I wonder if anyone's ever encoded a resource reference directly into the finalizer. For example it could be `<name>.<namespace>.baremetalasset.midas.io` or something like that. If that's a bad idea for some reason, then perhaps just an annotation.

I guess I need to learn more about finalizers. What is the goal of the finalizer...to prevent the SyncSet from being deleted without the inventory controller knowing about it?

**Comment by sacharya** [comment]
> to prevent the SyncSet from being deleted without the inventory controller knowing about it?

In which case, the syncset will be created again. I am not sure we need that finalizer either. We can put a finalizer on BareMetalasset and ensure that SyncSet gets deleted upon BMA deletion.

**Comment by mhrivnak** [comment]
Good point. The finalizer is probably not needed on the SyncSet as long as the BMA reconcile loop will always ensure that a SyncSet exists, and as long as a watch handler is queueing the BMA when a SyncSet event happens.
